let Array = ["appel", 5, 3.1,3, true, 3, [6,10]];
let ArreyConCat = ["||",false, true]
let Size = Array.length;
console.log("original Size = " + Size);
console.log("----------------------");
let String = Array.toString();
console.log("everyting to Sring = " + String);
console.log("----------------------");
let Array3 = Array.at(2);
console.log("at Index 2 = " + Array3);
console.log("----------------------");
let Joined = Array.join(" - ");
console.log('Joined with (-) = ' + Joined);
console.log("----------------------");
let Popped = Array.pop();
console.log("number Popped = " + Popped);
console.log("----------------------");
let Pushed = Array.push(Popped);
console.log("lenght after Pushed = " + Pushed);
console.log("----------------------");
let Shifted = Array.shift();
console.log("String Shifted = " + Shifted);
console.log("----------------------");
let Unshifted = Array.unshift(Shifted);
console.log("lenght after Unshifted = " + Unshifted);
console.log("----------------------");
let Deleted = delete Array[4];
console.log("Array after Delete Index 2 = " + Array);
console.log("Deleted = " + Deleted);
console.log("----------------------");
let ArrayConcat = Array.concat(ArreyConCat);
console.log("Array after Concat = " + ArrayConcat);
console.log("----------------------");
let copiedIndex = Array.copyWithin(1,4);
console.log("Array after copyWithin = " + copiedIndex);
console.log("----------------------");
let flattened = Array.flat();
console.log("Array after flat = " + flattened);
console.log("----------------------");
let spliced = Array.splice(3,2,"banana","kiwi");
console.log("Array after splice from 2 to 3 = " + Array);
console.log("Spliced elements = " + spliced);
console.log("----------------------");
let tospliced = Array.toSpliced(1,4);
console.log("Array after toSpliced from 1 to 4 = " + tospliced);
console.log("----------------------");
let sliced = Array.slice(1,4);
console.log("Array after slice from 1 to 4 = " + sliced);
console.log("----------------------");
let IndexOf = Array.indexOf(3);
console.log("Index of 3 = " + IndexOf);
console.log("----------------------");
let LastIndexOf = Array.lastIndexOf(3);
console.log("Last Index of 3 = " + LastIndexOf);
console.log("----------------------");  
let includes = Array.includes(false);
console.log("Array includes true = " + includes);
console.log("----------------------");
let sorted = Array.sort();
console.log("Array after sort = " + sorted);
console.log("----------------------");
let reversed = Array.reverse();
console.log("Array after reverse = " + reversed);
console.log("----------------------");


console.log("Final Array = " + Array);
